# workflow名字
name: Publish to npm

# 触发条件：当 main 分支有 push 事件时触发
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  publish:
    # 在 Ubuntu 最新版本上运行作业
    runs-on: ubuntu-latest
    steps:
      # 使用 actions/checkout 检出当前代码
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install pnpm
        run: |
          npm install -g pnpm
          echo "PATH=$PATH"

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm run check
          pnpm run build

      - name: Add Npm Token
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ./.npmrc
          ls -al
          cat ./.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOOLS_CI_TOKEN }}
        with:
          branch: main
          publish: true
          version: pnpm run version
          commit: 'chore: version packages'
          title: 'chore: version packages'
          setupGitUser: true
          createGithubReleases: true

      - name: Publish
        run: pnpm publish
